### PR TITLE
Fix binary and data dir; remove log

### PR DESCRIPTION
**Pull request by maniackcrudelis**

### CODE REVIEW

**Comment by JimboJoe** [comment]
For log redirection, you can have a look here: https://github.com/YunoHost-Apps/cryptpad_ynh/blob/master/conf/systemd.service#L13

**Comment by JimboJoe** [comment]
OK, I just wanted to let you know 😉

**Comment by maniackcrudelis** [comment]
Indeed, and thank you to show me that, I had only seen some things about that.
But here, looks like something concrete.

Anyway, I opened an issue to keep that somewhere which it's can be seen.

**Comment by liberodark** [comment]
For what is not good ?

**Pull request closed without merging**
