### PR TITLE
[fix] check_process

### PR DESCRIPTION
**Pull request by Rafi594**
https://ci-apps.yunohost.org/jenkins/job/haste%20(Community)/1/consoleFull

### CODE REVIEW

**Comment by frju365** [comment]
perhaps we can force level 4, as we won't provide LDAP support.

**Comment by frju365** [comment]
Port already used must be enabled too.

**Comment by Rafi594** [comment]
I have modified port already used and force the level 4

**Comment by maniackcrudelis** [comment]
:)
As we need this app for our YunoHost infra.
I go ahead

**Pull request merged**
